### ISSUE TITLE
Example using a Timm model

### ISSUE THREAD

**Issue by kurtjcu** [jexio/fulmo#54]
**Is your feature request related to a problem? Please describe.**
Hi, 
your codebase would be more attractive to those exploring hydra/lightning/timm if you had a basic model (timm) and dataloader (imagenet from folders?)

**Comment by jexio** [comment]
@kurtjcu 
Hello, thank you for your interest in my project. I don't think I can propose anything good for the community...
This is a silly "fork" of `ashleve/lightning-hydra-template`  repository.

but if you want to see an example...
[G2Net Gravitational Wave Detection competition](https://github.com/jexio/g2net)
